/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolApp;



import methods.*;

/**
 *
 * @author Iredafe
 */
public class TeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TeacherDashboard
     */
    public TeacherDashboard() {
        initComponents();
    
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jTabbedPaneForHomeAndDashboard = new javax.swing.JTabbedPane();
        teacherHomeDashboardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myLectureHome = new javax.swing.JButton();
        myScheduleHome = new javax.swing.JButton();
        myAssessmentsHome = new javax.swing.JButton();
        studentGradesHome = new javax.swing.JButton();
        myExaminationsHome = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        MainDashboardPanel = new javax.swing.JPanel();
        topDashboard = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        leftDashboard = new javax.swing.JPanel();
        assessmentBtn = new javax.swing.JButton();
        examsBtn = new javax.swing.JButton();
        gradesBtn = new javax.swing.JButton();
        lectureBtn = new javax.swing.JButton();
        scheduleBtn = new javax.swing.JButton();
        subTopDashboard = new javax.swing.JPanel();
        settingsInSubTopPanel = new javax.swing.JLabel();
        labelForSubTopPanel = new javax.swing.JLabel();
        jTabbedPaneForTeacherDashboard = new javax.swing.JTabbedPane();
        lecturePanel = new javax.swing.JPanel();
        jTabbedPaneForLectureBtn = new javax.swing.JTabbedPane();
        addSubjectPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddLectureNotesTextField = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        uploadVideoPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton63 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        AddVideoTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        addToLibraryPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        AddToLibraryTextField = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        updateSubjectNotesPanel = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UpdateLectureNotesTextField = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        updateVideosPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        UpdateVideoTextField = new javax.swing.JTextField();
        jButton64 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        updateLibrary = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        UpdateLibraryTextField = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        viewSubjectPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton39 = new javax.swing.JButton();
        schedulePanel = new javax.swing.JPanel();
        assessmentPanel = new javax.swing.JPanel();
        examsPanel = new javax.swing.JPanel();
        gradesPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setMinimumSize(new java.awt.Dimension(1210, 655));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherHomeDashboardPanel.setBackground(new java.awt.Color(0, 102, 102));
        teacherHomeDashboardPanel.setMinimumSize(new java.awt.Dimension(1210, 640));
        teacherHomeDashboardPanel.setPreferredSize(new java.awt.Dimension(1210, 640));
        teacherHomeDashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/black teacher.png"))); // NOI18N
        teacherHomeDashboardPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 810, 490));

        myLectureHome.setBackground(new java.awt.Color(153, 255, 153));
        myLectureHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myLectureHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/presentation (1).png"))); // NOI18N
        myLectureHome.setText("My Lectures");
        myLectureHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myLectureHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myLectureHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myLectureHomeActionPerformed(evt);
            }
        });
        teacherHomeDashboardPanel.add(myLectureHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 120));

        myScheduleHome.setBackground(new java.awt.Color(153, 255, 153));
        myScheduleHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myScheduleHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/work schedule.png"))); // NOI18N
        myScheduleHome.setText("My Schedule");
        myScheduleHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myScheduleHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myScheduleHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myScheduleHomeActionPerformed(evt);
            }
        });
        teacherHomeDashboardPanel.add(myScheduleHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 120));

        myAssessmentsHome.setBackground(new java.awt.Color(153, 255, 153));
        myAssessmentsHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myAssessmentsHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/report.png"))); // NOI18N
        myAssessmentsHome.setText("My Assessments");
        myAssessmentsHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAssessmentsHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myAssessmentsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAssessmentsHomeActionPerformed(evt);
            }
        });
        teacherHomeDashboardPanel.add(myAssessmentsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 110));

        studentGradesHome.setBackground(new java.awt.Color(153, 255, 153));
        studentGradesHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        studentGradesHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/score.png"))); // NOI18N
        studentGradesHome.setText("Student Grades");
        studentGradesHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        studentGradesHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        studentGradesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentGradesHomeActionPerformed(evt);
            }
        });
        teacherHomeDashboardPanel.add(studentGradesHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 160, 120));

        myExaminationsHome.setBackground(new java.awt.Color(153, 255, 153));
        myExaminationsHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myExaminationsHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/reunion.png"))); // NOI18N
        myExaminationsHome.setText("My Examinations");
        myExaminationsHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myExaminationsHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myExaminationsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myExaminationsHomeActionPerformed(evt);
            }
        });
        teacherHomeDashboardPanel.add(myExaminationsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 160, 110));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton5.setText("Log Out");
        teacherHomeDashboardPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Welcome To");
        teacherHomeDashboardPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));

        jLabel3.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ABC GROUP OF SCHOOLS");
        teacherHomeDashboardPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel30.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Teachers' Portal");
        teacherHomeDashboardPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jTabbedPaneForHomeAndDashboard.addTab("tab1", teacherHomeDashboardPanel);

        MainDashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topDashboard.setBackground(new java.awt.Color(0, 102, 102));
        topDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        topDashboard.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 150, 40));
        topDashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 40, 40));

        MainDashboardPanel.add(topDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 80));

        leftDashboard.setBackground(new java.awt.Color(0, 102, 102));
        leftDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assessmentBtn.setBackground(new java.awt.Color(153, 255, 153));
        assessmentBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        assessmentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Apps-Google-Analytics-icon.png"))); // NOI18N
        assessmentBtn.setText("Assessment");
        assessmentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        assessmentBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        assessmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentBtnActionPerformed(evt);
            }
        });
        leftDashboard.add(assessmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 70));

        examsBtn.setBackground(new java.awt.Color(153, 255, 153));
        examsBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        examsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/examination.png"))); // NOI18N
        examsBtn.setText("Exams");
        examsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        examsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        examsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examsBtnActionPerformed(evt);
            }
        });
        leftDashboard.add(examsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 70));

        gradesBtn.setBackground(new java.awt.Color(153, 255, 153));
        gradesBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        gradesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/checklist.png"))); // NOI18N
        gradesBtn.setText("Grades");
        gradesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gradesBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gradesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradesBtnActionPerformed(evt);
            }
        });
        leftDashboard.add(gradesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 70));

        lectureBtn.setBackground(new java.awt.Color(153, 255, 153));
        lectureBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lectureBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/presentation (2).png"))); // NOI18N
        lectureBtn.setText("Lecture");
        lectureBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lectureBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lectureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureBtnActionPerformed(evt);
            }
        });
        leftDashboard.add(lectureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 70));

        scheduleBtn.setBackground(new java.awt.Color(153, 255, 153));
        scheduleBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        scheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/administration.png"))); // NOI18N
        scheduleBtn.setText("Schedule");
        scheduleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scheduleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });
        leftDashboard.add(scheduleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 70));

        MainDashboardPanel.add(leftDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 540));

        subTopDashboard.setBackground(new java.awt.Color(0, 153, 153));
        subTopDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        subTopDashboard.add(settingsInSubTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        labelForSubTopPanel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        labelForSubTopPanel.setForeground(new java.awt.Color(255, 255, 255));
        subTopDashboard.add(labelForSubTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 120, 30));

        MainDashboardPanel.add(subTopDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1010, 50));

        jTabbedPaneForTeacherDashboard.setMinimumSize(new java.awt.Dimension(1010, 590));
        jTabbedPaneForTeacherDashboard.setPreferredSize(new java.awt.Dimension(1010, 590));

        lecturePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneForLectureBtn.setBackground(new java.awt.Color(153, 255, 153));

        addSubjectPanel.setBackground(new java.awt.Color(153, 255, 153));
        addSubjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel32.setText("Lecture Notes");
        addSubjectPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 20));

        jButton8.setBackground(new java.awt.Color(0, 255, 153));
        jButton8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton8.setText("Attach");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, 40));

        jButton10.setBackground(new java.awt.Color(0, 255, 153));
        jButton10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/add.png"))); // NOI18N
        jButton10.setText("Insert");
        addSubjectPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 40));

        jTextField2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Notes");
        addSubjectPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Topics");
        addSubjectPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Subject Name");
        addSubjectPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));
        addSubjectPanel.add(AddLectureNotesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 280, 40));

        jButton11.setBackground(new java.awt.Color(0, 255, 153));
        jButton11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/update.png"))); // NOI18N
        jButton11.setText("Update Subject");
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addSubjectPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 450, 280));

        jButton13.setBackground(new java.awt.Color(0, 255, 153));
        jButton13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/subject.png"))); // NOI18N
        jButton13.setText("Save");
        jButton13.setToolTipText("Add Subject");
        addSubjectPanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 153));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jButton30.setBackground(new java.awt.Color(0, 255, 153));
        jButton30.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/video-player.png"))); // NOI18N
        jButton30.setText("Video");
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 70, -1));

        jButton31.setBackground(new java.awt.Color(0, 255, 153));
        jButton31.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Books-icon (1).png"))); // NOI18N
        jButton31.setText("Library");
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jButton32.setBackground(new java.awt.Color(0, 255, 153));
        jButton32.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton32.setText("View");
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        addSubjectPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 138, 280, 40));

        jButton40.setBackground(new java.awt.Color(0, 255, 153));
        jButton40.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton40.setText("Preview");
        addSubjectPanel.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jTabbedPaneForLectureBtn.addTab("tab1", addSubjectPanel);

        uploadVideoPanel.setBackground(new java.awt.Color(153, 255, 153));
        uploadVideoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel33.setText("Lecture Videos");
        uploadVideoPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 20));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        uploadVideoPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 360, 220));

        jButton63.setBackground(new java.awt.Color(0, 255, 153));
        jButton63.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/uploading-archive.png"))); // NOI18N
        jButton63.setText("Upload");
        jButton63.setToolTipText("Upload");
        uploadVideoPanel.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, 40));

        jButton18.setBackground(new java.awt.Color(51, 255, 153));
        jButton18.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton18.setText("Home");
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jButton9.setBackground(new java.awt.Color(51, 255, 153));
        jButton9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/watch video.png"))); // NOI18N
        jButton9.setText("Watch Video");
        jButton9.setToolTipText("Watch Video");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 120, 60));

        jButton12.setBackground(new java.awt.Color(51, 255, 153));
        jButton12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Books-icon (1).png"))); // NOI18N
        jButton12.setText("e-Library ");
        jButton12.setToolTipText("e-Library ");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, -1));
        uploadVideoPanel.add(AddVideoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 300, 40));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel14.setText("Add Video:");
        uploadVideoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        uploadVideoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 300, 120));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel15.setText("Description:");
        uploadVideoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel16.setText("Video Name");
        uploadVideoPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel17.setText("Preview Video");
        uploadVideoPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jButton33.setBackground(new java.awt.Color(0, 255, 153));
        jButton33.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton33.setText("View");
        jButton33.setToolTipText("View");
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jButton35.setBackground(new java.awt.Color(0, 255, 153));
        jButton35.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/update icon1.png"))); // NOI18N
        jButton35.setText("Update Video");
        jButton35.setToolTipText("Update Video");
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jButton34.setBackground(new java.awt.Color(51, 255, 153));
        jButton34.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton34.setText("Attach");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, 40));

        jTabbedPaneForLectureBtn.addTab("tab2", uploadVideoPanel);

        addToLibraryPanel.setBackground(new java.awt.Color(153, 255, 153));
        addToLibraryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel12.setText("Subject");
        addToLibraryPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jTextField5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 40));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel13.setText("Author Name:");
        addToLibraryPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 20));
        addToLibraryPanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 40));

        jButton16.setBackground(new java.awt.Color(0, 255, 153));
        jButton16.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton16.setText("Attach");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 40));

        jButton17.setBackground(new java.awt.Color(0, 255, 153));
        jButton17.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/update.png"))); // NOI18N
        jButton17.setText("Update Library");
        jButton17.setToolTipText("Update Library");
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 130, -1));

        jButton19.setBackground(new java.awt.Color(0, 255, 153));
        jButton19.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton19.setText("View");
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addToLibraryPanel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        jButton20.setBackground(new java.awt.Color(0, 255, 153));
        jButton20.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/x-button.png"))); // NOI18N
        jButton20.setText("Delete Book");
        addToLibraryPanel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 140, 50));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel21.setText("e-Library");
        addToLibraryPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject", "Book Title", "Author", "File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        addToLibraryPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 470, 90));

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel22.setText("Upload PDF:");
        addToLibraryPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));
        addToLibraryPanel.add(AddToLibraryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 270, 40));

        jButton21.setBackground(new java.awt.Color(0, 255, 153));
        jButton21.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/uploading-archive.png"))); // NOI18N
        jButton21.setText("Upload Book");
        jButton21.setToolTipText("Upload Book");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 50));

        jComboBox3.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addToLibraryPanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, 40));

        jLabel34.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel34.setText("Book Name:");
        addToLibraryPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jButton2.setBackground(new java.awt.Color(0, 255, 153));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setToolTipText("Home");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, -1, -1));

        jButton36.setBackground(new java.awt.Color(0, 255, 153));
        jButton36.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/subject.png"))); // NOI18N
        jButton36.setText("Add Subject");
        jButton36.setToolTipText("Add Subject");
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        addToLibraryPanel.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 110, -1));

        jTabbedPaneForLectureBtn.addTab("tab3", addToLibraryPanel);

        updateSubjectNotesPanel.setBackground(new java.awt.Color(153, 255, 153));
        updateSubjectNotesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        updateSubjectNotesPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Update Notes");
        updateSubjectNotesPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 20));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setText("Select Subject:");
        updateSubjectNotesPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel10.setText("Topic:");
        updateSubjectNotesPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        UpdateLectureNotesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateLectureNotesTextFieldActionPerformed(evt);
            }
        });
        updateSubjectNotesPanel.add(UpdateLectureNotesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, 40));

        jButton14.setBackground(new java.awt.Color(0, 255, 153));
        jButton14.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/uploading-archive.png"))); // NOI18N
        jButton14.setText("Upload");
        jButton14.setToolTipText("Upload");
        updateSubjectNotesPanel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 40));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel11.setText("Update Notes");
        updateSubjectNotesPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        updateSubjectNotesPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 340, 250));

        jButton15.setBackground(new java.awt.Color(0, 255, 153));
        jButton15.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton15.setText("Attach");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        updateSubjectNotesPanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, 40));

        jButton3.setBackground(new java.awt.Color(0, 255, 153));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton3.setText("Home");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        updateSubjectNotesPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jButton37.setBackground(new java.awt.Color(0, 255, 153));
        jButton37.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton37.setText("View");
        jButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton37.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        updateSubjectNotesPanel.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jTabbedPaneForLectureBtn.addTab("tab4", updateSubjectNotesPanel);

        updateVideosPanel.setBackground(new java.awt.Color(153, 255, 153));
        updateVideosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel19.setText("Update Videos");
        updateVideosPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 255, 153));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton4.setText("Home");
        jButton4.setToolTipText("Home");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        updateVideosPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel36.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel36.setText("Video Name:");
        updateVideosPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane7.setViewportView(jTextArea2);

        updateVideosPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, 120));

        jLabel37.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel37.setText("Description:");
        updateVideosPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel38.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel38.setText("File:");
        updateVideosPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));
        updateVideosPanel.add(UpdateVideoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 320, 40));

        jButton64.setBackground(new java.awt.Color(0, 255, 153));
        jButton64.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton64.setText("Attach");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        updateVideosPanel.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, 40));

        jComboBox5.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        updateVideosPanel.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 40));

        jButton28.setBackground(new java.awt.Color(0, 255, 153));
        jButton28.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/update icon1.png"))); // NOI18N
        jButton28.setText("Update");
        jButton28.setToolTipText("Update");
        updateVideosPanel.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, 40));

        jButton29.setBackground(new java.awt.Color(0, 255, 153));
        jButton29.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/x-button.png"))); // NOI18N
        jButton29.setText("Delete");
        jButton29.setToolTipText("Delete");
        updateVideosPanel.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 40));

        jLabel39.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel39.setText("Preview Video:");
        updateVideosPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        updateVideosPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 350, 260));

        jButton38.setBackground(new java.awt.Color(0, 255, 153));
        jButton38.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton38.setText("View");
        jButton38.setToolTipText("View");
        jButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton38.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        updateVideosPanel.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jTabbedPaneForLectureBtn.addTab("tab5", updateVideosPanel);

        updateLibrary.setBackground(new java.awt.Color(153, 255, 153));
        updateLibrary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel18.setText("Update e-Library");
        updateLibrary.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        updateLibrary.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 30));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel20.setText("Select Book:");
        updateLibrary.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextField10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        updateLibrary.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, 40));

        jLabel24.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel24.setText("Book Name:");
        updateLibrary.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel25.setText("Author Name:");
        updateLibrary.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 20));
        updateLibrary.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, 40));

        jLabel26.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel26.setText("Upload PDF:");
        updateLibrary.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 20));
        updateLibrary.add(UpdateLibraryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 290, 40));

        jButton22.setBackground(new java.awt.Color(0, 255, 153));
        jButton22.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/attach icon.png"))); // NOI18N
        jButton22.setText("Attach");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        updateLibrary.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, 30));

        jButton23.setBackground(new java.awt.Color(0, 255, 153));
        jButton23.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/uploading-archive.png"))); // NOI18N
        jButton23.setText("Upload Book");
        jButton23.setToolTipText("Upload Book");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        updateLibrary.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, 50));

        jTable2.setBackground(new java.awt.Color(255, 255, 153));
        jTable2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        updateLibrary.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 470, 90));

        jButton24.setBackground(new java.awt.Color(0, 255, 153));
        jButton24.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/subject.png"))); // NOI18N
        jButton24.setText("Add Subject");
        jButton24.setToolTipText("Add Subject");
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        updateLibrary.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, -1));

        jButton25.setBackground(new java.awt.Color(0, 255, 153));
        jButton25.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/x-button.png"))); // NOI18N
        jButton25.setText("Delete Book");
        jButton25.setToolTipText("Delete Book");
        updateLibrary.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 50));

        jButton26.setBackground(new java.awt.Color(0, 255, 153));
        jButton26.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/eye.png"))); // NOI18N
        jButton26.setText("View");
        jButton26.setToolTipText("View");
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        updateLibrary.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 255, 153));
        jButton6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton6.setText("Home");
        jButton6.setToolTipText("Home");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        updateLibrary.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        jTabbedPaneForLectureBtn.addTab("tab6", updateLibrary);

        viewSubjectPanel.setBackground(new java.awt.Color(153, 255, 153));
        viewSubjectPanel.setMinimumSize(new java.awt.Dimension(990, 490));
        viewSubjectPanel.setPreferredSize(new java.awt.Dimension(990, 490));
        viewSubjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel27.setText("View");
        viewSubjectPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewSubjectPanel.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 30));

        jLabel28.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel28.setText("Watch Video:");
        viewSubjectPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 30));

        jButton7.setBackground(new java.awt.Color(0, 255, 153));
        jButton7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/x-button.png"))); // NOI18N
        jButton7.setText("Delete Subject");
        jButton7.setToolTipText("Delete Subject");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        viewSubjectPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        viewSubjectPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, 110));

        jLabel35.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel35.setText("Select Subject:");
        viewSubjectPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        viewSubjectPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 350, 210));

        jLabel29.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel29.setText("Videos:");
        viewSubjectPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton27.setBackground(new java.awt.Color(0, 255, 153));
        jButton27.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Actions-home-icon.png"))); // NOI18N
        jButton27.setText("Home");
        jButton27.setToolTipText("Home");
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        viewSubjectPanel.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jScrollPane6.setViewportView(jEditorPane1);

        viewSubjectPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 440, 350));

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel23.setText("Notes:");
        viewSubjectPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        viewSubjectPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 120, 110));

        jButton39.setBackground(new java.awt.Color(0, 255, 153));
        jButton39.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/subject.png"))); // NOI18N
        jButton39.setText("Add Subject");
        jButton39.setToolTipText("Add Subject");
        jButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton39.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        viewSubjectPanel.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 110, -1));

        jTabbedPaneForLectureBtn.addTab("tab7", viewSubjectPanel);

        lecturePanel.add(jTabbedPaneForLectureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1010, 540));

        jTabbedPaneForTeacherDashboard.addTab("tab1", lecturePanel);
        jTabbedPaneForTeacherDashboard.addTab("tab2", schedulePanel);
        jTabbedPaneForTeacherDashboard.addTab("tab3", assessmentPanel);

        examsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneForTeacherDashboard.addTab("tab4", examsPanel);

        gradesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneForTeacherDashboard.addTab("tab5", gradesPanel);

        MainDashboardPanel.add(jTabbedPaneForTeacherDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1010, 560));

        jTabbedPaneForHomeAndDashboard.addTab("tab2", MainDashboardPanel);

        getContentPane().add(jTabbedPaneForHomeAndDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1210, 700));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myLectureHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myLectureHomeActionPerformed

        //this button calls the panel for students
        jTabbedPaneForHomeAndDashboard.setSelectedIndex(1);
        jTabbedPaneForTeacherDashboard.setSelectedIndex(0);
        labelForSubTopPanel.setText("My Lectures");

        // TODO add your handling code here:
    }//GEN-LAST:event_myLectureHomeActionPerformed

    private void myScheduleHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myScheduleHomeActionPerformed

        //this button calls the panel for schedule
        jTabbedPaneForHomeAndDashboard.setSelectedIndex(1);
        jTabbedPaneForTeacherDashboard.setSelectedIndex(1);
        labelForSubTopPanel.setText("My Schedule");

        // TODO add your handling code here:
    }//GEN-LAST:event_myScheduleHomeActionPerformed

    private void myAssessmentsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAssessmentsHomeActionPerformed

        //this button calls the panel for assignments
        jTabbedPaneForHomeAndDashboard.setSelectedIndex(1);
        jTabbedPaneForTeacherDashboard.setSelectedIndex(2);
        labelForSubTopPanel.setText("My Assessments");

        // TODO add your handling code here:
    }//GEN-LAST:event_myAssessmentsHomeActionPerformed

    private void studentGradesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGradesHomeActionPerformed

        //this button calls the panel for grades
        jTabbedPaneForHomeAndDashboard.setSelectedIndex(1);
        jTabbedPaneForTeacherDashboard.setSelectedIndex(4);
        labelForSubTopPanel.setText("Student Grades");

        // TODO add your handling code here:
    }//GEN-LAST:event_studentGradesHomeActionPerformed

    private void myExaminationsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myExaminationsHomeActionPerformed

        //this button calls the panel for exams
        jTabbedPaneForHomeAndDashboard.setSelectedIndex(1);
        jTabbedPaneForTeacherDashboard.setSelectedIndex(3);
        labelForSubTopPanel.setText("My Examinations");

        // TODO add your handling code here:
    }//GEN-LAST:event_myExaminationsHomeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
BrowseFile myfile = new BrowseFile();
myfile.AttachFile(AddLectureNotesTextField);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        jTabbedPaneForLectureBtn.setSelectedIndex(1);

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
BrowseFile myfile = new BrowseFile();
myfile.AttachFile(AddToLibraryTextField);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
BrowseFile myfile = new BrowseFile();
myfile.AttachFile(UpdateLibraryTextField);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void lectureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureBtnActionPerformed

jTabbedPaneForTeacherDashboard.setSelectedIndex(0);
jTabbedPaneForLectureBtn.setSelectedIndex(0);
labelForSubTopPanel.setText("My Lectures");

        // TODO add your handling code here:
    }//GEN-LAST:event_lectureBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
jTabbedPaneForTeacherDashboard.setSelectedIndex(1);
labelForSubTopPanel.setText("My Schedules");


        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void assessmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentBtnActionPerformed
jTabbedPaneForTeacherDashboard.setSelectedIndex(2);
labelForSubTopPanel.setText("My Assessments");


        // TODO add your handling code here:
    }//GEN-LAST:event_assessmentBtnActionPerformed

    private void examsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examsBtnActionPerformed

        jTabbedPaneForTeacherDashboard.setSelectedIndex(3);
        labelForSubTopPanel.setText("My examinations");


        // TODO add your handling code here:
    }//GEN-LAST:event_examsBtnActionPerformed

    private void gradesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradesBtnActionPerformed
        
jTabbedPaneForTeacherDashboard.setSelectedIndex(4);
labelForSubTopPanel.setText("Student Grades");



// TODO add your handling code here:
    }//GEN-LAST:event_gradesBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 
jTabbedPaneForHomeAndDashboard.setSelectedIndex(0);
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
jTabbedPaneForLectureBtn.setSelectedIndex(3);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
jTabbedPaneForLectureBtn.setSelectedIndex(2);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(6);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(4);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(6);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(1);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(5);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(6);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(6);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(6);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
jTabbedPaneForLectureBtn.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void UpdateLectureNotesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateLectureNotesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateLectureNotesTextFieldActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

jTabbedPaneForLectureBtn.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
BrowseFile myfileUpdate = new BrowseFile();
myfileUpdate.AttachFile1(UpdateLectureNotesTextField);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
BrowseFile myvideo = new BrowseFile();
myvideo.AttachFile2(AddVideoTextField);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed


BrowseFile myvideo = new BrowseFile();
myvideo.AttachFile2(UpdateVideoTextField);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton64ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddLectureNotesTextField;
    private javax.swing.JTextField AddToLibraryTextField;
    private javax.swing.JTextField AddVideoTextField;
    private javax.swing.JPanel MainDashboardPanel;
    private javax.swing.JTextField UpdateLectureNotesTextField;
    private javax.swing.JTextField UpdateLibraryTextField;
    private javax.swing.JTextField UpdateVideoTextField;
    private javax.swing.JPanel addSubjectPanel;
    private javax.swing.JPanel addToLibraryPanel;
    private javax.swing.JButton assessmentBtn;
    private javax.swing.JPanel assessmentPanel;
    private javax.swing.JButton examsBtn;
    private javax.swing.JPanel examsPanel;
    private javax.swing.JButton gradesBtn;
    private javax.swing.JPanel gradesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPaneForHomeAndDashboard;
    private javax.swing.JTabbedPane jTabbedPaneForLectureBtn;
    private javax.swing.JTabbedPane jTabbedPaneForTeacherDashboard;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelForSubTopPanel;
    private javax.swing.JButton lectureBtn;
    private javax.swing.JPanel lecturePanel;
    private javax.swing.JPanel leftDashboard;
    private javax.swing.JButton myAssessmentsHome;
    private javax.swing.JButton myExaminationsHome;
    private javax.swing.JButton myLectureHome;
    private javax.swing.JButton myScheduleHome;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JLabel settingsInSubTopPanel;
    private javax.swing.JButton studentGradesHome;
    private javax.swing.JPanel subTopDashboard;
    private javax.swing.JPanel teacherHomeDashboardPanel;
    private javax.swing.JPanel topDashboard;
    private javax.swing.JPanel updateLibrary;
    private javax.swing.JPanel updateSubjectNotesPanel;
    private javax.swing.JPanel updateVideosPanel;
    private javax.swing.JPanel uploadVideoPanel;
    private javax.swing.JPanel viewSubjectPanel;
    // End of variables declaration//GEN-END:variables
}
